CREATE OR REPLACE TABLE `ENGINE_PULLYS` (
    `id` INT(10) NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL UNIQUE,
    `additional_torque` INT(10) NOT NULL,
    `additional_horsepower` INT(10) NOT NULL,
    `last_updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);


CREATE OR REPLACE TABLE `ECU` (
    `id` INT(10) NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL UNIQUE,
    `additional_torque` INT(10) NOT NULL,
    `additional_horsepower` INT(10) NOT NULL,
    `last_updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);


CREATE OR REPLACE TABLE `FORCED_INDUCTION` (
    `id` INT(10) NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL UNIQUE,
    `additional_torque` INT(10) NOT NULL,
    `additional_horsepower` INT(10) NOT NULL,
    `last_updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);


CREATE OR REPLACE TABLE `AIR_INTAKE` (
    `id` INT(10) NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL UNIQUE,
    `air_flow` FLOAT(10) NOT NULL,
    `additional_torque` INT(10) NOT NULL,
    `additional_horsepower` INT(10) NOT NULL,
    `last_updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);


CREATE OR REPLACE TABLE `ENGINE` (
    `id` INT(10) NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL UNIQUE,
    `rpm_range` INT(10) NOT NULL,
    `horsepower` INT(10) NOT NULL,
    `torque` INT(10) NOT NULL,
    `engine_pullys_id` INT(10) NULL,
    `ecu_id` INT(10) NULL,
    `forced_induction_id` INT(10) NULL,
    `air_intake_id` INT(10) NULL,
    FOREIGN KEY (`engine_pullys_id`) REFERENCES ENGINE_PULLYS(`id`),
    FOREIGN KEY (`ecu_id`) REFERENCES ECU(`id`),
    FOREIGN KEY (`forced_induction_id`) REFERENCES FORCED_INDUCTION(`id`),
    FOREIGN KEY (`air_intake_id`) REFERENCES AIR_INTAKE(`id`),
    `last_updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);


CREATE OR REPLACE TABLE `SUSPENSION` (
    `id` INT(10) NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL UNIQUE,
    `last_updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);


CREATE OR REPLACE TABLE `TIRES` (
    `id` INT(10) NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL UNIQUE,
    `friction_coefficient` FLOAT(10) NOT NULL,
    `last_updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);


CREATE OR REPLACE TABLE `TRANSMISSION` (

    `id` INT(10) NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL UNIQUE,
    `gear_1` FLOAT(10) NULL DEFAULT NULL,
    `gear_2` FLOAT(10) NULL DEFAULT NULL,
    `gear_3` FLOAT(10) NULL DEFAULT NULL,
    `gear_4` FLOAT(10) NULL DEFAULT NULL,
    `gear_5` FLOAT(10) NULL DEFAULT NULL,
    `gear_6` FLOAT(10) NULL DEFAULT NULL,
    `gear_7` FLOAT(10) NULL DEFAULT NULL,
    `gear_8` FLOAT(10) NULL DEFAULT NULL,
    `gear_9` FLOAT(10) NULL DEFAULT NULL,
    `gear_10` FLOAT(10) NULL DEFAULT NULL,
    `reverse` FLOAT(10) NULL DEFAULT NULL,
    `last_updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)

);


CREATE OR REPLACE TABLE `WHEELS` (
    `id` INT(10) NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL UNIQUE,
    `height` INT(10) NOT NULL,
    `width` INT(10) NOT NULL,
    `last_updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);


CREATE OR REPLACE TABLE `CAR` (
    `id` INT(10) NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL UNIQUE,
    `engine_id` INT(10) NULL DEFAULT NULL,
    `suspension_id` INT(10) NULL DEFAULT NULL,
    `tires_id` INT(10) NULL DEFAULT NULL,
    `transmission_id` INT(10) NULL DEFAULT NULL,
    `wheels_id` INT(10) NULL DEFAULT NULL,
    `last_updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`engine_id`) REFERENCES engine(`id`),
    FOREIGN KEY (`suspension_id`) REFERENCES suspension(`id`),
    FOREIGN KEY (`tires_id`) REFERENCES tires(`id`),
    FOREIGN KEY (`transmission_id`) REFERENCES transmission(`id`),
    FOREIGN KEY (`wheels_id`) REFERENCES wheels(`id`)
);